CREATE VIEW [dbo].EcOperationsByDate
	AS 
	select Id, SiteId, EC_MODEL, EC_SN, EC_TYPE,EC_HEIGHT, EC_EASTWARD_DIST, EC_NORTHWARD_DIST, EC_SAMPLING_INT,
EC_SA_HEAT, EC_SA_OFFSET_N, EC_SA_WIND_FORMAT, EC_SA_GILL_ALIGN, EC_SA_GILL_PCI, 
EC_GA_FLOW_RATE, EC_GA_LICOR_FM_SN, EC_GA_LICOR_TP_SN, EC_GA_LICOR_AIU_SN, EC_GA_CAL_CO2_ZERO, EC_GA_CAL_CO2_OFFSET, EC_GA_CAL_CO2_REF,
EC_GA_CAL_H2O_ZERO, EC_GA_CAL_TA, EC_LOGGER, EC_FILE, EC_COMMENT, XDATE FROM
(select Id, SiteId, EC_MODEL, EC_SN, EC_TYPE,EC_HEIGHT, EC_EASTWARD_DIST, EC_NORTHWARD_DIST, EC_SAMPLING_INT,
EC_SA_HEAT, EC_SA_OFFSET_N, EC_SA_WIND_FORMAT, EC_SA_GILL_ALIGN, EC_SA_GILL_PCI, 
EC_GA_FLOW_RATE, EC_GA_LICOR_FM_SN, EC_GA_LICOR_TP_SN, EC_GA_LICOR_AIU_SN, EC_GA_CAL_CO2_ZERO, EC_GA_CAL_CO2_OFFSET, EC_GA_CAL_CO2_REF,
EC_GA_CAL_H2O_ZERO, EC_GA_CAL_TA, EC_LOGGER, EC_FILE, EC_COMMENT, EC_DATE as XDATE
from GRP_EC where DataStatus=0 AND EC_DATE is not null
Union 
select Id, SiteId, EC_MODEL, EC_SN, EC_TYPE,EC_HEIGHT, EC_EASTWARD_DIST, EC_NORTHWARD_DIST, EC_SAMPLING_INT,
EC_SA_HEAT, EC_SA_OFFSET_N, EC_SA_WIND_FORMAT, EC_SA_GILL_ALIGN, EC_SA_GILL_PCI, 
EC_GA_FLOW_RATE, EC_GA_LICOR_FM_SN, EC_GA_LICOR_TP_SN, EC_GA_LICOR_AIU_SN, EC_GA_CAL_CO2_ZERO, EC_GA_CAL_CO2_OFFSET, EC_GA_CAL_CO2_REF,
EC_GA_CAL_H2O_ZERO, EC_GA_CAL_TA, EC_LOGGER, EC_FILE, EC_COMMENT, EC_DATE_START as XDATE
from GRP_EC where DataStatus=0 AND EC_DATE_START is not null) AS ECT where ECT.SiteId>0
--AND [EC_TYPE] IN ('installation','Maintenance','removal') 
GROUP BY Id, SiteId, EC_MODEL, EC_SN, EC_TYPE,EC_HEIGHT, EC_EASTWARD_DIST, EC_NORTHWARD_DIST, EC_SAMPLING_INT,
EC_SA_HEAT, EC_SA_OFFSET_N, EC_SA_WIND_FORMAT, EC_SA_GILL_ALIGN, EC_SA_GILL_PCI, 
EC_GA_FLOW_RATE, EC_GA_LICOR_FM_SN, EC_GA_LICOR_TP_SN, EC_GA_LICOR_AIU_SN, EC_GA_CAL_CO2_ZERO, EC_GA_CAL_CO2_OFFSET, EC_GA_CAL_CO2_REF,
EC_GA_CAL_H2O_ZERO, EC_GA_CAL_TA, EC_LOGGER, EC_FILE, EC_COMMENT, XDATE
